version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - ls dyff
        - env
        - aws eks update-kubeconfig --name $CLUSTER_NAME

destroy:
  steps:
    setupVariables:
      after: *login-k8s
