version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - aws eks --region=us-east-1 update-kubeconfig --name $CLUSTER_NAME

destroy:
  steps:
    setupVariables:
      after: *login-k8s
