apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0

apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret1
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0


apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret2
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0
