apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret111
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0

---

apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret112
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0

---

apiVersion: v1
kind: Secret
metadata:
  name: yaron-test-secret113
data:
  bla: YmFzZTY0
  bla2: YmFzZTY0

---

apiVersion: v1
kind: Pod
metadata:
  name: static-web
spec:
  containers:
    - name: web
      image: nginx
