name: Add PR Reviewers

on:
  issue_comment:
    types: [created]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '/review' }}
    steps:
      - name: Set PR Reviewers
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: 'PR Reviewers'
